apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: ashok8639289986/tomcat-fronend:v1
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-mysql-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: ashok8639289986/tomcat-mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678"
            - name: MYSQL_DATABASE
              value: "mysql"
            - name: MYSQL_USER
              value: "12345678"
            - name: MYSQL_PASSWORD
              value: "12345678"
            - name: DB_HOST
              value: "mysql.cdxd2n1ta3y4.ap-south-1.rds.amazonaws.com"
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-mysql
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080    
  type: LoadBalancer

